Repository uasoft-indonesia/badaso, pull requests merged in 2021-04, with the labels that each got.

#60 Apply fixes from StyleCI
  src/Badaso.php
  src/Config/firebase.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoFCMController.php
  src/Controllers/BadasoFCMMessagesController.php
  src/Helpers/Firebase/FCMNotification.php
  src/Helpers/Firebase/FirebasePublishFile.php
  src/Migrations/2021_04_23_024729_add_notification_on_event_in_data_types_table.php
  src/Migrations/2021_04_26_014032_create_firebase_cloud_messages_table.php
  src/Migrations/2021_04_28_004319_create_f_c_m_messages_table.php
  src/Models/FCMMessage.php
  src/Models/FirebaseCloudMessages.php
  src/Models/Role.php
  src/resources/lang/en/notification.php
  src/resources/lang/id/notification.php
Labels: backend

#59 Feature/firebase
  composer.json
  src/Badaso.php
  src/Commands/BadasoFirebaseCommand.php
  src/Config/badaso.php
  src/Config/firebase.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoFCMController.php
  src/Controllers/BadasoFCMMessagesController.php
  src/Helpers/Firebase/FCMNotification.php
  src/Helpers/Firebase/FirebasePublishFile.php
  src/Migrations/2021_04_23_024729_add_notification_on_event_in_data_types_table.php
  src/Migrations/2021_04_26_014032_create_firebase_cloud_messages_table.php
  src/Migrations/2021_04_28_004319_create_f_c_m_messages_table.php
  src/Models/FCMMessage.php
  src/Models/FirebaseCloudMessages.php
  src/Models/FirebaseServices.php
  src/Models/InitUserFcm.php
  src/Models/Role.php
  src/Providers/BadasoServiceProvider.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso-fcm.js
  src/resources/js/app.js
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/pages/auth/login.vue
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/firebase/edit.vue
  src/resources/js/pages/home.vue
  src/resources/js/pages/index.vue
  src/resources/js/pages/notification/browse.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/utils/firebase.js
  src/resources/lang/en/notification.php
  src/resources/lang/id/notification.php
Labels: backend, feature, frontend

#61 Prepare alpha.33
  composer.json
  src/Badaso.php
  src/Commands/BadasoFirebaseCommand.php
  src/Config/badaso.php
  src/Config/firebase.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoFCMController.php
  src/Controllers/BadasoFCMMessagesController.php
  src/Helpers/Firebase/FCMNotification.php
  src/Helpers/Firebase/FirebasePublishFile.php
  src/Migrations/2021_04_23_024729_add_notification_on_event_in_data_types_table.php
  src/Migrations/2021_04_26_014032_create_firebase_cloud_messages_table.php
  src/Migrations/2021_04_28_004319_create_f_c_m_messages_table.php
  src/Models/FCMMessage.php
  src/Models/FirebaseCloudMessages.php
  src/Models/FirebaseServices.php
  src/Models/InitUserFcm.php
  src/Models/Role.php
  src/Providers/BadasoServiceProvider.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso-fcm.js
  src/resources/js/app.js
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/pages/auth/login.vue
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/firebase/edit.vue
  src/resources/js/pages/home.vue
  src/resources/js/pages/index.vue
  src/resources/js/pages/notification/browse.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/utils/firebase.js
  src/resources/lang/en/notification.php
  src/resources/lang/id/notification.php
Labels: backend, frontend

#62 Version bump
  bin/bump-version.sh
  composer.json
  src/resources/js/layout/admin/footer/Footer.vue
Labels: dependencies, frontend

#63 Bug fix release drafter
  .github/release-drafter.yml
Labels: config
