Repository uasoft-indonesia/badaso, pull requests merged in 2021-09, with the labels that each got.

#345 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
Labels: backend

#347 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
Labels: backend

#350 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
Labels: backend

#342 Remove null API on swagger | Fix issue #339
  src/Swagger/swagger_models/settings/badaso.php
Labels: enhancement, backend

#344 Add tooltip on input | Fix issue #300
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
  src/resources/js/assets/scss/module/_switch.scss
  src/resources/js/assets/scss/module/_text.scss
  src/resources/js/assets/scss/page/_crud-management.scss
  src/resources/js/components/BadasoSwitch.vue
  src/resources/js/components/BadasoText.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/menu-management/add.vue
  src/resources/js/pages/menu-management/edit.vue
  src/resources/js/pages/permission-management/add.vue
  src/resources/js/pages/permission-management/edit.vue
  src/resources/js/pages/user-management/add.vue
  src/resources/js/pages/user-management/edit.vue
Labels: frontend, backend, feature

#355 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
Labels: backend

#357 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
Labels: backend

#360 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
Labels: backend

#346 Add tooltip | Fix issue #300
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
  src/resources/js/assets/scss/module/_switch.scss
  src/resources/js/assets/scss/module/_text.scss
  src/resources/js/assets/scss/page/_crud-management.scss
  src/resources/js/components/BadasoSwitch.vue
  src/resources/js/components/BadasoText.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/menu-management/add.vue
  src/resources/js/pages/menu-management/edit.vue
  src/resources/js/pages/permission-management/add.vue
  src/resources/js/pages/permission-management/edit.vue
  src/resources/js/pages/user-management/add.vue
  src/resources/js/pages/user-management/edit.vue
Labels: frontend, backend, feature

#349 Add error alert when something wrong | Issue #340
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/Firebase/FCMNotification.php
  src/OrchestratorHandlers/CRUDDataAddedHandler.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/OrchestratorHandlers/CRUDDataUpdatedHandler.php
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
Labels: frontend, backend, bugfix

#361 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
Labels: backend

#362 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
Labels: backend

#354 Pointer cursor at table action hover
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/resources/js/assets/scss/module/_dropdown.scss
Labels: enhancement, backend

#356 Pointer cursor at table action hover
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/resources/js/assets/scss/module/_dropdown.scss
Labels: enhancement, backend

#364 Apply fixes from StyleCI
  src/Commands/AdminCommand.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoFileController.php
  src/Database/Schema/Index.php
  src/Database/Schema/SchemaManager.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/PermissionsSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
Labels: backend

#365 Fix always allow
  src/Helpers/AuthenticatedUser.php
  src/Seeder/Configurations/PermissionsSeeder.php
Labels: backend, bugfix

#366 Fix parsing notification on crud management
  src/resources/js/pages/crud-management/edit.vue
Labels: frontend, bugfix

#367 Fix parsing notification on crud management
  src/resources/js/pages/crud-management/edit.vue
Labels: frontend, bugfix

#370 Update composer.json
  composer.json
Labels: dependencies

#372 Update composer.json
  composer.json
Labels: dependencies

#373 Prepare for 2.0.0
  composer.json
Labels: dependencies

#376 Apply fixes from StyleCI
  src/Config/l5-swagger.php
  src/Config/lfm.php
  src/Config/log-viewer.php
  src/Config/sanctum.php
  src/Controllers/BadasoAuthController.php
  src/Helpers/ApiResponse.php
  src/Helpers/TokenManagement.php
  src/Middleware/BadasoAuthenticate.php
  src/Middleware/BadasoAuthenticateIframe.php
  src/Middleware/BadasoCheckPermissions.php
  src/Middleware/BadasoCheckPermissionsForCRUD.php
  src/Models/PersonalAccessToken.php
  src/Providers/BadasoServiceProvider.php
  src/Routes/web.php
Labels: backend

#379 Apply fixes from StyleCI
  src/Controllers/BadasoTableController.php
  src/Helpers/ApiResponse.php
Labels: backend

#381 Apply fixes from StyleCI
  src/Helpers/ApiResponse.php
Labels: backend

#382 Apply fixes from StyleCI
  src/Badaso.php
  src/Config/badaso-hidden-tables.php
Labels: backend

#383 Apply fixes from StyleCI
  src/Config/badaso-hidden-tables.php
Labels: backend

#380 [v2] remove date type in crud generate
  src/Badaso.php
  src/Config/badaso-hidden-tables.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoTableController.php
  src/Helpers/ApiResponse.php
  src/Helpers/WatchTableConfig.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso-table.js
  src/resources/js/app.js
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse-bin.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/crud-generated/sort.vue
Labels: frontend, backend

#384 Apply fixes from StyleCI
  src/Config/lfm.php
  src/Config/log-viewer.php
  src/Middleware/BadasoAuthenticate.php
  src/Middleware/BadasoAuthenticateIframe.php
Labels: backend

#375 Task/sanctum token
  README.md
  composer.json
  src/Badaso.php
  src/Commands/BadasoSetup.php
  src/Config/badaso-hidden-tables.php
  src/Config/badaso.php
  src/Config/l5-swagger.php
  src/Config/lfm.php
  src/Config/log-viewer.php
  src/Config/sanctum.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoFCMMessagesController.php
  src/Controllers/BadasoTableController.php
  src/Helpers/ApiResponse.php
  src/Helpers/AuthenticatedUser.php
  src/Helpers/TokenManagement.php
  src/Helpers/WatchTableConfig.php
  src/Middleware/BadasoAuthenticate.php
  src/Middleware/BadasoAuthenticateIframe.php
  src/Middleware/BadasoCheckPermissions.php
  src/Middleware/BadasoCheckPermissionsForCRUD.php
  src/Middleware/CheckForMaintenanceMode.php
  src/Migrations/2019_12_14_000001_create_personal_access_tokens_table.php
  src/Models/PersonalAccessToken.php
  src/Models/User.php
  src/Providers/BadasoServiceProvider.php
  src/Routes/api.php
  src/Routes/web.php
  src/Swagger/swagger_models/upload-file.php
  src/Swagger/swagger_models/user.php
  src/resources/js/api/modules/badaso-table.js
  src/resources/js/app.js
  src/resources/js/assets/scss/module/_switch.scss
  src/resources/js/assets/scss/module/_text.scss
  src/resources/js/assets/scss/page/_crud-management.scss
  src/resources/js/components/BadasoSwitch.vue
  src/resources/js/components/BadasoText.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/auth/login.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse-bin.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/crud-generated/sort.vue
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/menu-management/add.vue
  src/resources/js/pages/menu-management/edit.vue
  src/resources/js/pages/permission-management/add.vue
  src/resources/js/pages/permission-management/edit.vue
  src/resources/js/pages/user-management/add.vue
  src/resources/js/pages/user-management/edit.vue
  src/stubs/migration.stub
Labels: frontend, backend, dependencies

#387 Update BadasoSetup.php
  src/Commands/BadasoSetup.php
Labels: backend

#388 Update BadasoSetup.php
  src/Commands/BadasoSetup.php
Labels: backend

#389 Update BadasoSetup.php
  src/Commands/BadasoSetup.php
Labels: backend

#390 update composer jwt
  composer.json
Labels: dependencies
