Repository uasoft-indonesia/badaso, pull requests merged in 2021-05, with the labels that each got.

#65 Apply fixes from StyleCI
  src/Config/hidden-tables.php
  src/Config/l5-swagger.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoMenuController.php
  src/Helpers/ApiDocs.php
  src/Models/swagger_models/settings/badaso.php
  src/Providers/BadasoServiceProvider.php
Labels: backend

#64 feature/api-documentation & feature/badaso-blog-module-integration
  composer.json
  src/Badaso.php
  src/Commands/BadasoSetup.php
  src/Config/badaso.php
  src/Config/hidden-tables.php
  src/Config/l5-swagger.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoMenuController.php
  src/Helpers/ApiDocs.php
  src/Models/swagger_models/settings/badaso.php
  src/Providers/BadasoServiceProvider.php
  src/Routes/api.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/PermissionsSeeder.php
  src/resources/js/api/index.js
  src/resources/js/api/modules/badaso-file.js
  src/resources/js/app.js
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoText.vue
  src/resources/js/components/BadasoTextarea.vue
  src/resources/js/lang/index.js
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/router/admin/admin-router.js
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/admin/generated-router.js
  src/resources/js/router/router.js
  src/resources/js/store/modules/badaso.js
  src/resources/js/store/store.js
Labels: backend, dependencies, frontend

#67 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#66 Feature/worker js
  src/Commands/BadasoFirebaseCommand.php
  src/Commands/BadasoSetup.php
  src/Config/hidden-tables.php
  src/Controllers/BadasoFCMMessagesController.php
  src/Controllers/BadasoMenuController.php
  src/Helpers/Firebase/FirebasePublishFile.php
  src/Providers/BadasoServiceProvider.php
  src/Routes/api.php
  src/resources/js/api/before-request.js
  src/resources/js/api/handle-error.js
  src/resources/js/api/index.js
  src/resources/js/api/modules/badaso-fcm.js
  src/resources/js/api/resource.js
  src/resources/js/app.js
  src/resources/js/apps/App.vue
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/lang/index.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/data-pending-add/browse.vue
  src/resources/js/pages/data-pending-edit/read.vue
  src/resources/js/pages/file-manager/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/pages/log-viewer/browse.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/router.js
  src/resources/js/store/modules/badaso.js
  src/resources/js/store/store.js
  src/resources/js/utils/broadcast-messages.js
  src/resources/js/utils/check-connection.js
  src/resources/js/utils/firebase.js
  src/resources/js/utils/indexed-db.js
  src/resources/views/admin-panel/index.blade.php
Labels: backend, frontend

#70 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
Labels: backend

#69 add new components
  src/Controllers/BadasoMenuController.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso-menu.js
  src/resources/js/components/BadasoCollapse.vue
  src/resources/js/components/BadasoCollapseItem.vue
  src/resources/js/store/modules/badaso.js
  src/resources/js/store/store.js
Labels: backend, bugfix, frontend

#72 Apply fixes from StyleCI
  src/Config/badaso.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoMaintenanceController.php
  src/Middleware/ApiRequest.php
  src/Middleware/CheckForMaintenanceMode.php
  src/Migrations/2021_05_07_024347_add_is_maintenance_to_data_types_table.php
  src/Models/Permission.php
  src/Models/User.php
Labels: backend

#74 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#75 Apply fixes from StyleCI
  src/Seeder/Setup/RolePermissionsSeeder.php
Labels: backend

#76 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#73 Feature/easy installer
  composer.json
  src/Commands/BadasoSetup.php
  src/Helpers/Firebase/FCMNotification.php
  src/Helpers/Firebase/FirebasePublishFile.php
  src/resources/js/app.js
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/utils/broadcast-messages.js
Labels: backend, dependencies, feature, frontend

#77 feature/analytics with excluded routes
  composer.json
  src/Commands/BadasoSetup.php
  src/Config/analytics.php
  src/Providers/BadasoServiceProvider.php
  src/resources/js/app.js
  src/resources/js/router/excludeRouter.js
Labels: backend, dependencies, feature, frontend

#79 set dependencies and env
  src/Commands/BadasoSetup.php
Labels: backend, bugfix

#81 api docs wrapper
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/api-documentation/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/admin/configuration-router.js
Labels: backend, feature, frontend

#82 better message
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/database-management/browse.vue
  src/resources/js/pages/database-management/edit.vue
Labels: bugfix, frontend

#80 fixing export pdf not match column
  src/resources/js/pages/crud-generated/browse.vue
Labels: bugfix, frontend

#83 bugfix for api-docs 404
  src/Commands/BadasoSetup.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
Labels: backend, bugfix

#87 fix composer for analytics
  composer.json
Labels: bugfix, dependencies

#88 Prepare for alpha.34
  composer.json
Labels: dependencies

#89 Merge develop to master
  composer.json
  src/resources/js/layout/admin/footer/Footer.vue
Labels: dependencies, frontend

#91 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#90 bugfix firebase if empty env and version footer
  src/resources/js/app.js
  src/resources/js/layout/admin/footer/Footer.vue
Labels: backend, frontend

#92 Prepare to alpha.35
  src/resources/js/app.js
  src/resources/js/layout/admin/footer/Footer.vue
Labels: frontend

#93 Bump version to alpha.35
  composer.json
Labels: dependencies

#96 Apply fixes from StyleCI
  src/BadasoDeploymentOrchestrator.php
  src/Controllers/BadasoCRUDController.php
  src/Helpers/HiddenWatchTableConfig.php
Labels: backend

#98 Remove analytics from composer
  composer.json
Labels: bugfix, dependencies

#99 Apply fixes from StyleCI
  src/Helpers/HiddenTableConfig.php
  src/Helpers/WatchTableConfig.php
Labels: backend

#95 Feature/config watch table
  src/Badaso.php
  src/BadasoDeploymentOrchestrator.php
  src/Config/badaso-hidden-tables.php
  src/Config/badaso-watch-tables.php
  src/Config/badaso.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Helpers/HiddenTableConfig.php
  src/Helpers/WatchTableConfig.php
  src/Providers/BadasoServiceProvider.php
Labels: backend, feature, frontend

#100 Merge develop to main
  composer.json
  src/Badaso.php
  src/BadasoDeploymentOrchestrator.php
  src/Config/badaso-hidden-tables.php
  src/Config/badaso-watch-tables.php
  src/Config/badaso.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Helpers/HiddenTableConfig.php
  src/Helpers/WatchTableConfig.php
  src/Migrations/2021_03_05_093223_create_activity_log_table.php
  src/Providers/BadasoServiceProvider.php
  src/resources/js/components/BadasoEditor.vue
Labels: backend, dependencies, frontend

#101 Merge develop to main
  README.md
  composer.json
Labels: dependencies

#102 remove publish tinymce
  src/Commands/BadasoSetup.php
Labels: backend

#104 Apply fixes from StyleCI
  src/Helpers/HiddenTableConfig.php
  src/Helpers/WatchTableConfig.php
Labels: backend

#108 Change "MIX_BADASO_PLUGINS" > "MIX_BADASO_MODULES"
  src/resources/js/api/index.js
  src/resources/js/app.js
  src/resources/js/lang/index.js
  src/resources/js/router/router.js
  src/resources/js/store/store.js
Labels: bugfix, frontend

#110 bump version to 1.0.0-alpha.37
  composer.json
Labels: dependencies

#115 Apply fixes from StyleCI
  src/ContentManager/FileSystem.php
Labels: backend

#114 Database Seeder and Pwa
  src/Config/badaso.php
  src/ContentManager/FileSystem.php
  src/Controllers/BadasoDashboardController.php
  src/Images/badaso-images/logo-144px.png
  src/Images/badaso-images/logo-192px.png
  src/Images/badaso-images/logo-512px.png
  src/Providers/BadasoServiceProvider.php
  src/Routes/web.php
  src/Seeder/CRUDData/BadasoDeploymentOrchestratorSeeder.php
  src/resources/js/router/router.js
  src/resources/views/admin-panel/index.blade.php
Labels: backend, feature, frontend

#116 fix composer versioning
  composer.json
Labels: bugfix, dependencies

#120 Apply fixes from StyleCI
  src/BadasoDeploymentOrchestrator.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
  src/Controllers/BadasoCRUDController.php
Labels: backend

#119 Feature/pwa installation
  src/Config/badaso.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
Labels: backend, feature

#118 Change dashboard prefix
  src/Config/badaso.php
  src/Config/l5-swagger.php
  src/resources/js/app.js
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/auth/forgot-password.vue
  src/resources/js/pages/auth/login.vue
  src/resources/js/pages/auth/register.vue
  src/resources/js/pages/auth/reset-password.vue
  src/resources/js/pages/auth/verify.vue
  src/resources/js/router/admin/admin-router.js
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/admin/generated-router.js
  src/resources/js/router/auth/auth-router.js
  src/resources/js/router/router.js
  src/resources/js/store/modules/badaso.js
Labels: backend, bugfix, frontend

#121 Merge develop to main
  composer.json
  src/Config/badaso.php
  src/Config/l5-swagger.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
  src/Controllers/BadasoDashboardController.php
  src/Images/badaso-images/logo-144px.png
  src/Images/badaso-images/logo-192px.png
  src/Images/badaso-images/logo-512px.png
  src/Providers/BadasoServiceProvider.php
  src/Routes/web.php
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
  src/resources/js/app.js
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/auth/forgot-password.vue
  src/resources/js/pages/auth/login.vue
  src/resources/js/pages/auth/register.vue
  src/resources/js/pages/auth/reset-password.vue
  src/resources/js/pages/auth/verify.vue
  src/resources/js/router/admin/admin-router.js
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/admin/generated-router.js
  src/resources/js/router/auth/auth-router.js
  src/resources/js/router/router.js
  src/resources/js/store/modules/badaso.js
  src/resources/views/admin-panel/index.blade.php
Labels: backend, dependencies, frontend

#122 change seeder path
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
Labels: backend, feature

#125 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#124 Bugfix Env and Sidebar scroll
  src/Commands/BadasoSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/utils/helper.js
Labels: backend, frontend

#126 Merge develop to main
  README.md
  src/Commands/BadasoSetup.php
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
  src/resources/js/app.js
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/utils/helper.js
Labels: backend, frontend
