Repository uasoft-indonesia/badaso, pull requests merged in 2021-08, with the labels that each got.

#301 Enhancement on badaso core configuration (Resolve #294)
  src/Config/badaso.php
  src/Models/User.php
  src/Seeder/Configurations/BadasoSeeder.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/resources/js/pages/configuration/add.vue
  src/resources/js/pages/configuration/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/store/modules/badaso.js
Labels: backend, enhancement, frontend

#305 Apply fixes from StyleCI
  src/Helpers/MigrationParser.php
Labels: backend

#303 Enhancement on badaso core configuration (Resolve #294)
  src/Config/badaso.php
  src/Models/User.php
  src/Seeder/Configurations/BadasoSeeder.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/resources/js/assets/scss/module/_collapse-item.scss
  src/resources/js/assets/scss/module/_collapse.scss
  src/resources/js/components/BadasoCollapseItem.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/pages/configuration/add.vue
  src/resources/js/pages/configuration/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/store/modules/badaso.js
Labels: backend, enhancement, frontend

#299 [v2] no license key
  src/Config/badaso.php
  src/Controllers/BadasoDashboardController.php
  src/Helpers/MigrationParser.php
  src/Middleware/VerifyLicense.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso.js
  src/resources/js/apps/App.vue
  src/resources/js/pages/auth/login.vue
  src/resources/js/store/modules/badaso.js
Labels: backend, frontend

#298 no lincense key
  src/Config/badaso.php
  src/Controllers/BadasoDashboardController.php
  src/Middleware/VerifyLicense.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso.js
  src/resources/js/apps/App.vue
  src/resources/js/pages/auth/login.vue
  src/resources/js/store/modules/badaso.js
Labels: backend, frontend

#306 Prepare 2.0.0-rc.12
  README.md
  src/Config/badaso.php
  src/Models/User.php
  src/Seeder/Configurations/BadasoSeeder.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/resources/js/assets/scss/module/_collapse-item.scss
  src/resources/js/assets/scss/module/_collapse.scss
  src/resources/js/components/BadasoCollapseItem.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/pages/configuration/add.vue
  src/resources/js/pages/configuration/browse.vue
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/store/modules/badaso.js
Labels: backend, frontend

#308 Apply fixes from StyleCI
  src/Controllers/BadasoFileController.php
  src/Helpers/ApiResponse.php
  src/Helpers/HandleFile.php
Labels: backend

#309 Apply fixes from StyleCI
  src/Controllers/BadasoFileController.php
Labels: backend

#307 Change concept for media getters (Resolve #295)
  src/Helpers/ApiResponse.php
  src/Helpers/HandleFile.php
  src/Images/badaso-images/thumbs/auth-bg.jpg
  src/Images/badaso-images/thumbs/badaso.png
  src/Images/badaso-images/thumbs/default-user.png
  src/Images/badaso-images/thumbs/favicon.png
  src/Images/badaso-images/thumbs/logo-144px.png
  src/Images/badaso-images/thumbs/logo-192px.png
  src/Images/badaso-images/thumbs/logo-512px.png
  src/Images/badaso-images/thumbs/logo.png
  src/Images/badaso-images/thumbs/logo.webp
  src/Images/badaso-images/thumbs/maintenance.png
  src/Middleware/ApiRequest.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/resources/js/assets/scss/module/_upload-file-multiple.scss
  src/resources/js/assets/scss/module/_upload-file.scss
  src/resources/js/assets/scss/module/_upload-image-multiple.scss
  src/resources/js/assets/scss/module/_upload-image.scss
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/layout/auth/Container.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse-bin.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/crud-generated/sort.vue
  src/resources/js/pages/maintenance.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/store/modules/badaso.js
Labels: backend, enhancement, frontend

#313 Apply fixes from StyleCI
  src/Helpers/HandleFile.php
Labels: backend

#314 Apply fixes from StyleCI
  src/Helpers/HandleFile.php
Labels: backend

#312 Change concept for media getters (Resolve #295)
  src/Helpers/ApiResponse.php
  src/Helpers/HandleFile.php
  src/Images/badaso-images/thumbs/auth-bg.jpg
  src/Images/badaso-images/thumbs/badaso.png
  src/Images/badaso-images/thumbs/default-user.png
  src/Images/badaso-images/thumbs/favicon.png
  src/Images/badaso-images/thumbs/logo-144px.png
  src/Images/badaso-images/thumbs/logo-192px.png
  src/Images/badaso-images/thumbs/logo-512px.png
  src/Images/badaso-images/thumbs/logo.png
  src/Images/badaso-images/thumbs/logo.webp
  src/Images/badaso-images/thumbs/maintenance.png
  src/Middleware/ApiRequest.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/resources/js/assets/scss/module/_upload-file-multiple.scss
  src/resources/js/assets/scss/module/_upload-file.scss
  src/resources/js/assets/scss/module/_upload-image-multiple.scss
  src/resources/js/assets/scss/module/_upload-image.scss
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/layout/auth/Container.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse-bin.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/crud-generated/sort.vue
  src/resources/js/pages/maintenance.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/router.js
  src/resources/js/store/modules/badaso.js
Labels: enhancement, frontend, backend

#315 Add newly filemanager concept support for post-module
  src/Helpers/HandleFile.php
Labels: enhancement, backend

#316 Prepare 2.0.0-rc.12
  src/Helpers/ApiResponse.php
  src/Helpers/HandleFile.php
  src/Images/badaso-images/thumbs/auth-bg.jpg
  src/Images/badaso-images/thumbs/badaso.png
  src/Images/badaso-images/thumbs/default-user.png
  src/Images/badaso-images/thumbs/favicon.png
  src/Images/badaso-images/thumbs/logo-144px.png
  src/Images/badaso-images/thumbs/logo-192px.png
  src/Images/badaso-images/thumbs/logo-512px.png
  src/Images/badaso-images/thumbs/logo.png
  src/Images/badaso-images/thumbs/logo.webp
  src/Images/badaso-images/thumbs/maintenance.png
  src/Middleware/ApiRequest.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
  src/resources/js/assets/scss/module/_upload-file-multiple.scss
  src/resources/js/assets/scss/module/_upload-file.scss
  src/resources/js/assets/scss/module/_upload-image-multiple.scss
  src/resources/js/assets/scss/module/_upload-image.scss
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/layout/auth/Container.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse-bin.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/crud-generated/sort.vue
  src/resources/js/pages/maintenance.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/store/modules/badaso.js
Labels: frontend, backend

#317 Prepare 2.0.0-rc.12
  README.md
  composer.json
Labels: dependencies

#319 Apply fixes from StyleCI
  src/Swagger/swagger_models/upload-file.php
  src/Swagger/swagger_models/user.php
Labels: backend

#320 Add fetch on configuration api
  src/Controllers/BadasoConfigurationsController.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso-configuration.js
Labels: frontend, backend, feature

#318 Task/swagger upload file
  src/Swagger/swagger_models/upload-file.php
  src/Swagger/swagger_models/user.php
Labels: backend

#323 Apply fixes from StyleCI
  src/Controllers/BadasoConfigurationsController.php
Labels: backend

#322 Add fetch on configuration api
  src/Controllers/BadasoConfigurationsController.php
  src/Routes/api.php
  src/Rules/ExistsModel.php
  src/resources/js/api/modules/badaso-configuration.js
Labels: frontend, backend, feature

#324 Fix some rules
  src/Rules/ExistsModel.php
Labels: backend, feature

#325 Prepare next release
  README.md
  src/Controllers/BadasoConfigurationsController.php
  src/Routes/api.php
  src/resources/js/api/modules/badaso-configuration.js
Labels: frontend, backend

#326 Bump to 2.0.0-rc.13
  composer.json
Labels: dependencies

#328 Move import css from app.js to style.scss
  src/Commands/BadasoSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/style.scss
  src/resources/views/admin-panel/index.blade.php
Labels: frontend, backend, bugfix

#330 Prepare next release
  src/Commands/BadasoSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/style.scss
  src/resources/views/admin-panel/index.blade.php
Labels: frontend, backend

#329 Move import css from app.js to style.scss
  src/Commands/BadasoSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/assets/scss/module/_date.scss
  src/resources/js/assets/scss/module/_datetime.scss
  src/resources/js/assets/scss/module/_time.scss
  src/resources/js/assets/scss/style.scss
  src/resources/views/admin-panel/index.blade.php
Labels: frontend, backend, bugfix

#332 Move tinymce css into style.scss
  src/resources/js/assets/scss/style.scss
  src/resources/js/components/BadasoCodeEditor.vue
  src/resources/js/components/BadasoEditor.vue
Labels: frontend, bugfix

#333 Move tinymce css into style.scss
  src/resources/js/assets/scss/style.scss
  src/resources/js/components/BadasoCodeEditor.vue
  src/resources/js/components/BadasoEditor.vue
Labels: frontend, bugfix

#334 Move style on vue file to scss
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/assets/scss/module/_notification-message.scss
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/public/Container.vue
Labels: frontend, bugfix

#335 Move vue style to scss
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/assets/scss/module/_notification-message.scss
  src/resources/js/assets/scss/page/_site-management.scss
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/public/Container.vue
  src/resources/js/pages/configuration/browse.vue
Labels: frontend, bugfix

#336 Prepare next release
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/assets/scss/module/_notification-message.scss
  src/resources/js/assets/scss/style.scss
  src/resources/js/components/BadasoCodeEditor.vue
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/public/Container.vue
Labels: frontend

#337 Bump version to 2.0.0-rc.14
  composer.json
Labels: dependencies
