Repository uasoft-indonesia/badaso, pull requests merged in 2021-07, with the labels that each got.

#229 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/ContentManager/ContentGenerator.php
  src/Helpers/WatchTableConfig.php
Labels: backend

#232 Apply fixes from StyleCI
  src/Helpers/ApiDocs.php
Labels: backend

#233 [badaso v1] add permission generate file docs and api-docs.json 0775
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
Labels: backend, bugfix

#234 [badaso v2] add permission generate file docs and api-docs.json 0775
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
Labels: backend, bugfix

#235 Merge develop to main
  composer.json
  src/Config/badaso.php
  src/Controllers/BadasoDashboardController.php
  src/Migrations/2020_11_13_064800_create_data_type.php
  src/Migrations/2020_11_18_014827_create_configurations.php
  src/Migrations/2020_11_18_014950_create_permissions.php
  src/Migrations/2020_11_18_015020_create_menus.php
  src/Migrations/2020_11_18_015341_add_badaso_user_field.php
  src/Migrations/2021_02_19_033756_add_icon_to_menus.php
  src/Migrations/2021_03_02_022959_add_column_to_permissions.php
  src/Migrations/2021_03_16_064043_add_can_delete_to_configurations.php
  src/Migrations/2021_04_23_024729_add_notification_on_event_in_data_types_table.php
  src/Migrations/2021_05_07_024347_add_is_maintenance_to_data_types_table.php
  src/Migrations/2021_06_14_091143_alter_avatar_field_on_user_table.php
  src/Migrations/2021_06_22_091143_alter_avatar_field_on_user_table_again.php
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, dependencies

#244 #241 Required timestamp
  src/resources/js/pages/database-management/add.vue
  src/resources/js/pages/database-management/edit.vue
Labels: enhancement, frontend

#223 add more props to widget
  src/Widgets/PermissionWidget.php
  src/Widgets/RoleWidget.php
  src/Widgets/UserWidget.php
  src/resources/js/pages/home.vue
Labels: backend, enhancement, frontend

#224 #212 add more props to widget
  src/Widgets/PermissionWidget.php
  src/Widgets/RoleWidget.php
  src/Widgets/UserWidget.php
  src/resources/js/pages/home.vue
Labels: backend, enhancement, frontend

#248 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/Controllers/BadasoCRUDController.php
Labels: backend

#251 Apply fixes from StyleCI
  src/Controllers/BadasoCRUDController.php
Labels: backend

#249 Fixing some bugfix
  src/resources/js/assets/scss/module/_collapse.scss
  src/resources/js/router/router.js
  src/resources/js/store/modules/badaso.js
Labels: bugfix, frontend

#247 [Badaso v1] Bugfix/v1/update name
  CONTRIBUTING.md
  composer.json
  composer.lock
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/Controllers/BadasoCRUDController.php
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
  src/resources/js/assets/scss/module/_collapse.scss
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
Labels: backend, bugfix, dependencies, frontend

#250 [Badaso v2] update name composer.json same update to v1
  CONTRIBUTING.md
  composer.json
  src/Controllers/BadasoCRUDController.php
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
Labels: backend, bugfix, dependencies, frontend

#252 Rebase develop to main
  CONTRIBUTING.md
  composer.json
  src/Controllers/BadasoCRUDController.php
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
  src/resources/js/pages/crud-management/add.vue
  src/resources/js/pages/crud-management/edit.vue
Labels: backend, dependencies, frontend

#256 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/Controllers/BadasoCRUDController.php
Labels: backend

#259 Merge develop to main
  composer.json
  src/Commands/BadasoSetup.php
Labels: backend, dependencies

#260 Bump version 2.0.0-rc.8
  composer.json
Labels: dependencies

#262 Apply fixes from StyleCI
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoDatabaseController.php
  src/Helpers/MigrationParser.php
Labels: backend

#261 Add foreign key & soft delete
  src/Badaso.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoDatabaseController.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/MigrationParser.php
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/assets/scss/module/_alert.scss
  src/resources/js/assets/scss/page/_database-management.scss
  src/resources/js/lang/modules/en.js
  src/resources/js/pages/database-management/add.vue
  src/resources/js/pages/database-management/edit.vue
  src/resources/js/utils/database-helper.js
Labels: backend, feature, frontend

#263 Add foreign key and soft delete
  src/Badaso.php
  src/ContentManager/FileGenerator.php
  src/Controllers/BadasoDatabaseController.php
  src/Database/Schema/SchemaManager.php
  src/Helpers/MigrationParser.php
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/assets/scss/module/_alert.scss
  src/resources/js/assets/scss/page/_database-management.scss
  src/resources/js/lang/modules/en.js
  src/resources/js/pages/database-management/add.vue
  src/resources/js/pages/database-management/edit.vue
  src/resources/js/utils/database-helper.js
Labels: backend, feature, frontend

#264 Fix typo on parameter
  src/resources/js/pages/database-management/add.vue
Labels: bugfix, frontend

#269 Apply fixes from StyleCI
  src/Badaso.php
  src/Commands/BadasoSetup.php
  src/Config/badaso.php
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoMenuController.php
  src/Controllers/BadasoRolePermissionController.php
  src/Controllers/BadasoTableController.php
  src/Controllers/BadasoUserRoleController.php
  src/Controllers/Controller.php
  src/Helpers/AuthenticatedUser.php
  src/Migrations/2020_11_12_000000_create_badaso_users_table.php
  src/Migrations/2020_11_12_100000_create_badaso_password_resets_table.php
  src/Migrations/2020_11_13_064800_create_data_type.php
  src/Migrations/2020_11_18_014827_create_configurations.php
  src/Migrations/2020_11_18_014939_create_roles.php
  src/Migrations/2020_11_18_014950_create_permissions.php
  src/Migrations/2020_11_18_015020_create_menus.php
  src/Migrations/2020_11_18_015029_create_menu_items.php
  src/Migrations/2020_11_18_015852_create_user_roles.php
  src/Migrations/2020_11_18_020028_create_role_permissions.php
  src/Migrations/2021_03_09_064445_create_user_verifications.php
  src/Migrations/2021_03_12_073541_create_email_resets.php
  src/Migrations/2021_04_26_014032_create_firebase_cloud_messages_table.php
  src/Migrations/2021_04_28_004319_create_f_c_m_messages_table.php
  src/Models/Configuration.php
  src/Models/DataRow.php
  src/Models/DataType.php
  src/Models/EmailReset.php
  src/Models/FCMMessage.php
  src/Models/FirebaseCloudMessages.php
  src/Models/Menu.php
  src/Models/MenuItem.php
  src/Models/PasswordReset.php
  src/Models/Permission.php
  src/Models/Role.php
  src/Models/RolePermission.php
  src/Models/User.php
  src/Models/UserRole.php
  src/Models/UserVerification.php
Labels: backend

#272 Apply fixes from StyleCI
  src/Migrations/2020_11_12_000000_create_badaso_users_table.php
  src/Migrations/2020_11_12_100000_create_password_resets_table.php
  src/Models/PasswordReset.php
Labels: backend

#276 Apply fixes from StyleCI
  src/Models/FirebaseCloudMessages.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/Traits/Uuid.php
Labels: backend

#274 Add composer.lock to gitignore
  .gitignore
Labels: enhancement

#273 add composer.lock on gitignore
  .gitignore
Labels: enhancement

#277 Make sure that seeder use id
  src/ContentManager/ContentManager.php
  src/Controllers/BadasoPermissionController.php
  src/Controllers/BadasoRoleController.php
  src/Migrations/2020_11_13_064800_create_data_type.php
  src/Migrations/2020_11_18_014827_create_configurations.php
  src/Migrations/2020_11_18_014939_create_roles.php
  src/Migrations/2020_11_18_014950_create_permissions.php
  src/Migrations/2020_11_18_015020_create_menus.php
  src/Migrations/2020_11_18_015029_create_menu_items.php
  src/Migrations/2020_11_18_015852_create_user_roles.php
  src/Migrations/2020_11_18_020028_create_role_permissions.php
  src/Migrations/2021_03_05_093223_create_activity_log_table.php
  src/Migrations/2021_03_09_064445_create_user_verifications.php
  src/Migrations/2021_03_12_073541_create_email_resets.php
  src/Migrations/2021_04_26_014032_create_firebase_cloud_messages_table.php
  src/Migrations/2021_04_28_004319_create_f_c_m_messages_table.php
  src/Models/Menu.php
  src/Models/MenuItem.php
  src/Models/RolePermission.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, enhancement

#280 Apply fixes from StyleCI
  src/Models/FirebaseCloudMessages.php
Labels: backend

#279 Make sure that seeder use id
  src/Controllers/BadasoPermissionController.php
  src/Controllers/BadasoRoleController.php
  src/Migrations/2020_11_12_100000_create_badaso_password_resets_table.php
  src/Migrations/2020_11_13_064800_create_data_type.php
  src/Migrations/2020_11_18_014827_create_configurations.php
  src/Migrations/2020_11_18_014939_create_roles.php
  src/Migrations/2020_11_18_014950_create_permissions.php
  src/Migrations/2020_11_18_015020_create_menus.php
  src/Migrations/2020_11_18_015029_create_menu_items.php
  src/Migrations/2020_11_18_015852_create_user_roles.php
  src/Migrations/2020_11_18_020028_create_role_permissions.php
  src/Migrations/2021_03_05_093223_create_activity_log_table.php
  src/Migrations/2021_03_09_064445_create_user_verifications.php
  src/Migrations/2021_03_12_073541_create_email_resets.php
  src/Migrations/2021_04_26_014032_create_firebase_cloud_messages_table.php
  src/Migrations/2021_04_28_004319_create_f_c_m_messages_table.php
  src/Models/FirebaseCloudMessages.php
  src/Models/Menu.php
  src/Models/MenuItem.php
  src/Models/RolePermission.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, enhancement

#283 Apply fixes from StyleCI
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoPermissionController.php
  src/Controllers/BadasoRoleController.php
  src/Controllers/BadasoRolePermissionController.php
  src/Controllers/BadasoUserController.php
  src/Rules/ExistsModel.php
  src/Rules/UniqueModel.php
  src/resources/lang/en/validation.php
  src/resources/lang/id/validation.php
Labels: backend

#282 Fix validation
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoConfigurationsController.php
  src/Controllers/BadasoDatabaseController.php
  src/Controllers/BadasoMenuController.php
  src/Controllers/BadasoPermissionController.php
  src/Controllers/BadasoRoleController.php
  src/Controllers/BadasoRolePermissionController.php
  src/Controllers/BadasoTableController.php
  src/Controllers/BadasoUserController.php
  src/Controllers/BadasoUserRoleController.php
  src/Rules/ExistsModel.php
  src/Rules/UniqueModel.php
  src/resources/lang/en/validation.php
  src/resources/lang/id/validation.php
Labels: backend, bugfix

#286 Apply fixes from StyleCI
  src/Swagger/swagger_models/auth.php
Labels: backend

#285 Resolve #284
  src/Providers/BadasoServiceProvider.php
  src/Swagger/swagger_models/auth.php
Labels: backend, feature

#287 Prepare 2.0.0-rc.10
  README.md
  src/Providers/BadasoServiceProvider.php
  src/Swagger/swagger_models/auth.php
Labels: backend

#288 Feature/v1/auth api docs
  src/Providers/BadasoServiceProvider.php
  src/Swagger/swagger_models/auth.php
  src/Swagger/swagger_models/settings/badaso.php
Labels: backend, dependencies, feature

#289 Bump 2.0.0-rc.10
  composer.json
Labels: dependencies

#292 Fix missing meta
  src/resources/js/store/modules/badaso.js
Labels: bugfix, frontend

#291 Fix missing meta
  src/Config/lfm.php
  src/resources/js/store/modules/badaso.js
Labels: backend, bugfix, frontend

#293 Prepare 2.0.0-rc.11
  composer.json
  src/Config/lfm.php
  src/resources/js/store/modules/badaso.js
Labels: backend, dependencies, frontend
