Repository uasoft-indonesia/badaso, pull requests merged in 2021-06, with the labels that each got.

#129 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#130 Merge develop to main
  src/resources/js/store/modules/badaso.js
Labels: frontend

#132 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#133 Merge develop to main
  src/resources/js/pages/auth/login.vue
Labels: frontend

#135 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#136 Merge develop to main
  src/Controllers/BadasoDashboardController.php
  src/resources/js/pages/auth/login.vue
Labels: backend, frontend

#137 Rebase develop with main
  composer.json
Labels: dependencies

#139 Apply fixes from StyleCI
  src/Controllers/BadasoConfigurationsController.php
  src/Traits/FileHandler.php
Labels: backend

#138 Bugfix/license
  src/Controllers/BadasoConfigurationsController.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/Traits/FileHandler.php
Labels: backend, bugfix

#140 Merge develop to main
  src/Controllers/BadasoConfigurationsController.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/Traits/FileHandler.php
Labels: backend

#142 Enhance navbar responsive and BEM css methodolgy
  src/resources/js/assets/scss/layout/_navbar.scss
  src/resources/js/components/BadasoNavbar.vue
  src/resources/js/components/BadasoNotificationMessage.vue
  src/resources/js/layout/admin/header/Navbar.vue
Labels: frontend

#145 Apply fixes from StyleCI
  src/Config/lfm.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoFileController.php
  src/Controllers/BadasoUserController.php
Labels: backend

#144 Feature/management file
  src/Config/lfm.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoFileController.php
  src/Controllers/BadasoUserController.php
  src/Routes/api.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/api/modules/badaso-file.js
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/site-management/browse.vue
  src/resources/js/pages/user/profile.vue
  src/resources/js/utils/helper.js
Labels: backend, feature, frontend

#146 Feature/management file
  src/Config/lfm.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoFileController.php
  src/Controllers/BadasoUserController.php
  src/Routes/api.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/api/modules/badaso-file.js
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/site-management/browse.vue
  src/resources/js/pages/user/profile.vue
  src/resources/js/utils/helper.js
Labels: backend, feature, frontend

#147 Merge develop to main
  src/Config/lfm.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoFileController.php
  src/Controllers/BadasoUserController.php
  src/Routes/api.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/api/modules/badaso-file.js
  src/resources/js/assets/scss/layout/_custom.scss
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/site-management/browse.vue
  src/resources/js/pages/user/profile.vue
  src/resources/js/utils/helper.js
Labels: backend, frontend

#149 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/Controllers/BadasoDatabaseController.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
Labels: backend

#148 Enhancement/badaso support laravel 8
  composer.json
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/Config/lfm.php
  src/ContentManager/FileSystem.php
  src/Controllers/BadasoDatabaseController.php
  src/Models/swagger_models/settings/badaso.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
  src/Seeder/Configurations/BadasoSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/PermissionsSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/assets/scss/bootstrap/_variables.scss
  src/resources/js/router/admin/admin-router.js
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/admin/generated-router.js
  src/resources/js/router/auth/auth-router.js
  src/resources/js/router/router.js
  src/stubs/data_seed.stub
  src/stubs/delete_seed.stub
  src/stubs/row_seed.stub
  src/stubs/seed.stub
Labels: backend, dependencies, frontend

#150 Merge develop to main
  composer.json
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/Config/lfm.php
  src/ContentManager/FileSystem.php
  src/Controllers/BadasoDatabaseController.php
  src/Models/swagger_models/settings/badaso.php
  src/OrchestratorHandlers/CRUDDataDeletedHandler.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
  src/Seeder/Configurations/BadasoSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/PermissionsSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/assets/scss/bootstrap/_variables.scss
  src/resources/js/router/admin/admin-router.js
  src/resources/js/router/admin/configuration-router.js
  src/resources/js/router/admin/generated-router.js
  src/resources/js/router/auth/auth-router.js
  src/resources/js/router/router.js
  src/stubs/data_seed.stub
  src/stubs/delete_seed.stub
  src/stubs/row_seed.stub
  src/stubs/seed.stub
Labels: backend, dependencies, frontend

#154 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#155 Merge develop to main
  src/Commands/BadasoSetup.php
  src/Seeder/CRUD/BadasoDeploymentOrchestratorSeeder.php
  src/Seeder/Configurations/BadasoSeeder.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/Seeder/Configurations/MenusSeeder.php
  src/Seeder/Configurations/PermissionsSeeder.php
  src/Seeder/Configurations/RolePermissionsSeeder.php
  src/Seeder/Configurations/RolesSeeder.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/stubs/data_seed.stub
  src/stubs/delete_seed.stub
  src/stubs/row_seed.stub
  src/stubs/seed.stub
Labels: backend

#157 Apply fixes from StyleCI
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
Labels: backend

#160 Apply fixes from StyleCI
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
Labels: backend

#156 Add main class from ManualGenerate Seeder
  src/Config/lfm.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/ManualGenerate/BadasoManualGenerateSeeder.php
Labels: backend, feature

#158 Enhancement on file manager
  src/Config/badaso.php
  src/Images/badaso-images/badaso-logo.png
  src/Providers/BadasoServiceProvider.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/app.js
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/utils/storage.js
  src/resources/views/admin-panel/index.blade.php
Labels: backend, enhancement, frontend

#159 BadasoManualGenerateSeeder.php
  composer.json
  src/ContentManager/ContentGenerator.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/ManualGenerate/BadasoManualGenerateSeeder.php
Labels: backend, dependencies, feature

#161 Merge develop to main
  src/ContentManager/ContentGenerator.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/ManualGenerate/BadasoManualGenerateSeeder.php
Labels: backend

#162 set callback for driver
  src/resources/js/utils/storage.js
Labels: enhancement, frontend

#164 change badaso logo display behavior
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/user-management/read.vue
Labels: enhancement, frontend

#166 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#168 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#167 [v1] set default value for file manager
  src/Commands/BadasoSetup.php
  src/Images/badaso-images/favicon.png
  src/Images/badaso-images/logo.png
  src/Migrations/2021_06_14_091143_alter_avatar_field_on_user_table.php
  src/Providers/BadasoServiceProvider.php
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/user-management/read.vue
Labels: backend, enhancement, frontend

#165 set default value for image
  src/Commands/BadasoSetup.php
  src/Images/badaso-images/favicon.png
  src/Images/badaso-images/logo.png
  src/Migrations/2021_06_14_091143_alter_avatar_field_on_user_table.php
  src/Providers/BadasoServiceProvider.php
Labels: backend

#169 Merge develop to main
  src/Commands/BadasoSetup.php
  src/Config/badaso.php
  src/Config/lfm.php
  src/Images/badaso-images/favicon.png
  src/Images/badaso-images/logo.png
  src/Migrations/2021_06_14_091143_alter_avatar_field_on_user_table.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/app.js
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/utils/storage.js
  src/resources/views/admin-panel/index.blade.php
Labels: backend, frontend

#171 change logo image display
  src/Images/badaso-images/logo.webp
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, enhancement

#170 change logo display
  src/Images/badaso-images/logo.webp
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, enhancement

#172 Merge develop to main
  src/Images/badaso-images/logo.webp
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend

#174 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/ContentManager/ContentGenerator.php
  src/ContentManager/ContentManager.php
  src/ContentManager/FileGenerator.php
  src/ContentManager/FileSystem.php
Labels: backend

#176 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
Labels: backend

#175 Generate Swagger
  src/Commands/BadasoSetup.php
Labels: backend

#177 Merge develop to main
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
Labels: backend

#182 #179 Change auth background
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/layout/auth/Container.vue
Labels: backend, feature, frontend

#181 #179 Change auth background
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/assets/scss/layout/_container.scss
  src/resources/js/layout/auth/Container.vue
Labels: backend, feature, frontend

#184 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoPermissionController.php
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
  src/Providers/BadasoServiceProvider.php
Labels: backend

#183 bugfix swagger authorize
  src/Commands/BadasoSetup.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoPermissionController.php
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
  src/Providers/BadasoServiceProvider.php
  src/Swagger/swagger_models/settings/badaso.php
Labels: backend, bugfix

#188 Apply fixes from StyleCI
  src/Controllers/BadasoFileController.php
  src/Helpers/ApiResponse.php
Labels: backend

#187 Apply fixes from StyleCI
  src/Controllers/BadasoFileController.php
  src/Helpers/ApiResponse.php
Labels: backend

#186 Add media base url meta
  src/Controllers/BadasoFileController.php
  src/Helpers/ApiResponse.php
  src/Migrations/2021_06_22_091143_alter_avatar_field_on_user_table_again.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/app.js
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/store/modules/badaso.js
  src/resources/js/utils/storage.js
Labels: backend, feature, frontend

#185 Add media base url meta
  src/Controllers/BadasoFileController.php
  src/Helpers/ApiResponse.php
  src/Migrations/2021_06_22_091143_alter_avatar_field_on_user_table_again.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/app.js
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoLogoDisplay.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/admin/Container.vue
  src/resources/js/layout/admin/header/Navbar.vue
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/activity-log/read.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/store/modules/badaso.js
  src/resources/js/utils/storage.js
Labels: backend, feature, frontend

#190 Bugfix/v2/remove storage
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/resources/js/layout/auth/Container.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/store/modules/badaso.js
Labels: backend, bugfix, frontend

#191 fix auth bg
  src/resources/js/layout/auth/Container.vue
Labels: bugfix, frontend

#195 Apply fixes from StyleCI
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/ContentManager/FileSystem.php
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
  src/Providers/BadasoServiceProvider.php
Labels: backend

#192 Bugfix/v1/swagger authorize
  src/Helpers/ApiDocs.php
  src/Middleware/GenerateForSwagger.php
Labels: backend, bugfix

#194 Bugfix/v2/swagger authorize
  composer.json
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoPermissionController.php
  src/Helpers/ApiDocs.php
  src/Images/badaso-images/badaso-logo.png
  src/Middleware/GenerateForSwagger.php
  src/Providers/BadasoServiceProvider.php
  src/Swagger/swagger_models/settings/badaso.php
  src/resources/js/app.js
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
Labels: backend, bugfix, dependencies, frontend

#196 remove Vue.prototype.$storage in app.js
  src/resources/js/app.js
Labels: bugfix, frontend

#199 Merge develop to main
  src/Commands/BadasoSetup.php
  src/Config/l5-swagger.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoPermissionController.php
  src/Helpers/ApiDocs.php
  src/Images/badaso-images/badaso-logo.png
  src/Middleware/GenerateForSwagger.php
  src/Providers/BadasoServiceProvider.php
  src/Seeder/Configurations/SiteManagementSeeder.php
  src/Swagger/swagger_models/settings/badaso.php
  src/resources/js/components/BadasoEditor.vue
  src/resources/js/components/BadasoUploadFile.vue
  src/resources/js/components/BadasoUploadFileMultiple.vue
  src/resources/js/components/BadasoUploadImage.vue
  src/resources/js/components/BadasoUploadImageMultiple.vue
  src/resources/js/layout/auth/Container.vue
  src/resources/js/pages/crud-generated/browse.vue
  src/resources/js/pages/crud-generated/read.vue
  src/resources/js/store/modules/badaso.js
Labels: backend, frontend

#200 Bump version to 2.0.0-rc.6
  composer.json
Labels: dependencies

#207 Create stale.yml
  .github/stale.yml
Labels: config

#218 #210 change seeder replace concept to delete
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, enhancement

#217 #210 change seeder replace concept to delete
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend, enhancement

#216 Squash migrations
  src/Migrations/2020_11_13_064800_create_data_type.php
  src/Migrations/2020_11_18_014827_create_configurations.php
  src/Migrations/2020_11_18_014950_create_permissions.php
  src/Migrations/2020_11_18_015020_create_menus.php
  src/Migrations/2020_11_18_015341_add_badaso_user_field.php
  src/Migrations/2021_02_19_033756_add_icon_to_menus.php
  src/Migrations/2021_03_02_022959_add_column_to_permissions.php
  src/Migrations/2021_03_16_064043_add_can_delete_to_configurations.php
  src/Migrations/2021_04_23_024729_add_notification_on_event_in_data_types_table.php
  src/Migrations/2021_05_07_024347_add_is_maintenance_to_data_types_table.php
  src/Migrations/2021_06_14_091143_alter_avatar_field_on_user_table.php
  src/Migrations/2021_06_22_091143_alter_avatar_field_on_user_table_again.php
Labels: backend, enhancement

#215 Squash migrations
  src/Migrations/2020_11_13_064800_create_data_type.php
  src/Migrations/2020_11_18_014827_create_configurations.php
  src/Migrations/2020_11_18_014950_create_permissions.php
  src/Migrations/2020_11_18_015020_create_menus.php
  src/Migrations/2020_11_18_015341_add_badaso_user_field.php
  src/Migrations/2021_02_19_033756_add_icon_to_menus.php
  src/Migrations/2021_03_02_022959_add_column_to_permissions.php
  src/Migrations/2021_03_16_064043_add_can_delete_to_configurations.php
  src/Migrations/2021_04_23_024729_add_notification_on_event_in_data_types_table.php
  src/Migrations/2021_05_07_024347_add_is_maintenance_to_data_types_table.php
  src/Migrations/2021_06_14_091143_alter_avatar_field_on_user_table.php
  src/Migrations/2021_06_22_091143_alter_avatar_field_on_user_table_again.php
Labels: backend, enhancement

#214 #208 Fixing license issue for badaso 1.x
  src/Config/badaso.php
  src/Controllers/BadasoDashboardController.php
Labels: backend, bugfix

#213 #208 Fixing license issue
  src/Config/badaso.php
  src/Controllers/BadasoDashboardController.php
Labels: backend, bugfix

#220 Apply fixes from StyleCI
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/Controller.php
  src/Migrations/2021_06_28_052154_add_field_is_soft_delete_in_data_types.php
  src/Routes/api.php
Labels: backend

#222 Apply fixes from StyleCI
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/Controller.php
  src/Helpers/ApiResponse.php
  src/Migrations/2021_06_28_052154_add_field_is_soft_delete_in_data_types.php
  src/Routes/api.php
  src/Seeder/Configurations/SiteManagementSeeder.php
Labels: backend
