Repository uasoft-indonesia/badaso, pull requests merged in 2021-10, with the labels that each got.

#393 Apply fixes from StyleCI
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
Labels: backend

#392 Add username to badaso
  src/Commands/AdminCommand.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoUserController.php
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
  src/Models/User.php
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/auth/register.vue
  src/resources/js/pages/user-management/add.vue
  src/resources/js/pages/user-management/edit.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/pages/user/profile.vue
  src/resources/views/mail/email-verification.blade.php
  src/resources/views/mail/forgot-password.blade.php
Labels: frontend, backend, feature

#396 Fix migration error
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
Labels: backend, bugfix

#398 Apply fixes from StyleCI
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
Labels: backend

#397 Add username to badaso
  src/Commands/AdminCommand.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoUserController.php
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
  src/Models/User.php
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/auth/register.vue
  src/resources/js/pages/user-management/add.vue
  src/resources/js/pages/user-management/edit.vue
  src/resources/js/pages/user-management/read.vue
  src/resources/js/pages/user/profile.vue
  src/resources/views/mail/email-verification.blade.php
  src/resources/views/mail/forgot-password.blade.php
Labels: frontend, backend, feature

#399 Fix migration error
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
Labels: bugfix

#400 Fix migration error
  src/Migrations/2021_09_29_094036_add_username_to_users_table.php
Labels: bugfix

#407 Apply fixes from StyleCI
  src/Migrations/2021_10_05_024140_rename_f_c_m_messages_table_to_notifications.php
Labels: backend

#409 Apply fixes from StyleCI
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoTableController.php
  src/Controllers/Controller.php
Labels: backend

#411 Apply fixes from StyleCI
  src/Controllers/BadasoTableController.php
  src/Controllers/Controller.php
Labels: backend

#412 Apply fixes from StyleCI
  src/Controllers/BadasoTableController.php
  src/Controllers/Controller.php
Labels: backend

#406 Rename FCM message to notification
  src/Controllers/BadasoNotificationsController.php
  src/Helpers/Firebase/FCMNotification.php
  src/Migrations/2021_10_05_024140_rename_f_c_m_messages_table_to_notifications.php
  src/Models/Notification.php
  src/Routes/api.php
Labels: backend, feature

#410 [v1] bugfix sqlite
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoTableController.php
  src/Controllers/Controller.php
Labels: backend, bugfix

#408 [v2] bugfix sqlite
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoTableController.php
  src/Controllers/Controller.php
Labels: backend, bugfix
