Repository uasoft-indonesia/badaso, pull requests merged in 2021-11, with the labels that each got.

#437 Apply fixes from StyleCI
  src/Config/badaso.php
Labels: backend

#436 #435 | Fix authentication
  src/Config/badaso.php
  src/Helpers/TokenManagement.php
Labels: backend, bugfix

#439 Apply fixes from StyleCI
  src/Controllers/BadasoBaseController.php
  src/Controllers/Controller.php
Labels: backend

#441 Apply fixes from StyleCI
  src/Controllers/Controller.php
Labels: backend

#440 Task/v2/replace api crud generate
  src/Controllers/BadasoBaseController.php
  src/Controllers/Controller.php
  src/Helpers/ApiDocs.php
  src/Swagger/swagger_models/auth.php
  src/resources/js/api/modules/badaso-entity.js
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/menu-management/browse.vue
Labels: frontend, backend

#438 replace api generate create or update
  src/Controllers/BadasoBaseController.php
  src/Controllers/Controller.php
  src/Helpers/ApiDocs.php
  src/Swagger/swagger_models/auth.php
  src/resources/js/api/modules/badaso-entity.js
  src/resources/js/pages/crud-generated/add.vue
  src/resources/js/pages/crud-generated/edit.vue
  src/resources/js/pages/menu-management/browse.vue
Labels: frontend, backend

#443 Apply fixes from StyleCI
  src/Controllers/Controller.php
Labels: backend

#444 update prefix menu table
  src/Migrations/2021_10_21_054710_add_is_show_header_and_expand_in_menus_table.php
Labels: backend

#449 Apply fixes from StyleCI
  src/Config/lfm.php
Labels: backend

#451 Apply fixes from StyleCI
  src/Config/lfm.php
Labels: backend

#453 Apply fixes from StyleCI
  src/Controllers/BadasoMaintenanceController.php
  src/Models/Configuration.php
Labels: backend

#455 Apply fixes from StyleCI
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoConfigurationsController.php
  src/Controllers/BadasoMaintenanceController.php
Labels: backend

#448 update config
  src/Config/lfm.php
Labels: backend, bugfix

#452 Bugfix/v2/maintenance
  composer.json
  src/Commands/BadasoSetup.php
  src/Config/lfm.php
  src/Controllers/BadasoConfigurationsController.php
  src/Controllers/BadasoMaintenanceController.php
  src/Helpers/Redis/ConfigurationRedis.php
  src/resources/js/app.js
  src/resources/js/router/router.js
Labels: frontend, backend, dependencies, bugfix

#454 update maintenance and sactum auth bug replace
  src/Commands/BadasoSetup.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoBaseController.php
  src/Controllers/BadasoCRUDController.php
  src/Controllers/BadasoConfigurationsController.php
  src/Controllers/BadasoFCMController.php
  src/Controllers/BadasoMaintenanceController.php
  src/Controllers/Controller.php
  src/Helpers/Firebase/FCMNotification.php
  src/Helpers/Redis/ConfigurationRedis.php
  src/Middleware/ApiRequest.php
  src/resources/js/router/router.js
Labels: frontend, backend, bugfix

#461 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
Labels: backend

#463 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
Labels: backend

#467 Apply fixes from StyleCI
  src/Models/MenuItem.php
Labels: backend

#471 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
Labels: backend

#468 Bugfix/v3/configuration page
  src/resources/js/pages/index.vue
  src/resources/js/router/admin/configuration-router.js
Labels: frontend, bugfix

#469 Bugfix/v2/configuration page
  src/resources/js/pages/index.vue
  src/resources/js/router/admin/configuration-router.js
Labels: frontend, bugfix

#473 Apply fixes from StyleCI
  src/Models/MenuItem.php
Labels: backend

#470 bugfix/v2/fixing-jspdf
  src/resources/js/pages/crud-generated/browse.vue
Labels: frontend, bugfix

#474 Bugfix/v3/fixing jspdf
  src/resources/js/pages/crud-generated/browse.vue
Labels: frontend, bugfix

#466 Bufix/v2/order seeder item
  src/Config/lfm.php
  src/ContentManager/ContentGenerator.php
  src/Controllers/BadasoMenuController.php
  src/Models/MenuItem.php
  src/resources/js/assets/scss/layout/_sidebar.scss
  src/resources/js/components/BadasoSidebarGroup.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/image-manager/browse.vue
  src/resources/js/store/modules/badaso.js
Labels: frontend, backend

#475 Update ConfigurationsSeeder.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
Labels: enhancement, backend

#476 Update ConfigurationsSeeder.php
  src/Seeder/Configurations/ConfigurationsSeeder.php
Labels: enhancement, backend

#478 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
Labels: backend

#480 Apply fixes from StyleCI
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoMenuController.php
  src/Models/MenuItem.php
Labels: backend

#479 update menu badaso
  src/Commands/BadasoSetup.php
  src/Config/lfm.php
  src/ContentManager/ContentGenerator.php
  src/Controllers/BadasoAuthController.php
  src/Controllers/BadasoMenuController.php
  src/Models/MenuItem.php
  src/Seeder/Configurations/FixedMenuItemSeeder.php
  src/resources/js/assets/scss/layout/_sidebar.scss
  src/resources/js/components/BadasoSidebarMenu.vue
  src/resources/js/components/BadasoSidebarMenuCallback.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/layout/admin/sidebar/SideBar.vue
  src/resources/js/pages/image-manager/browse.vue
  src/resources/js/store/modules/badaso.js
Labels: frontend, backend

#485 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
  src/Migrations/2021_11_25_100130_add_is_expand_in_badaso_menu_items_table.php
Labels: backend

#487 Apply fixes from StyleCI
  src/Controllers/BadasoMenuController.php
  src/Migrations/2021_11_25_100130_add_is_expand_in_badaso_menu_items_table.php
Labels: backend

#484 Task/v2/expand menu item
  src/Controllers/BadasoMenuController.php
  src/Migrations/2021_11_25_100130_add_is_expand_in_badaso_menu_items_table.php
  src/resources/js/assets/scss/page/_menu-management.scss
  src/resources/js/components/BadasoSidebarMenu.vue
  src/resources/js/components/BadasoSidebarMenuCallback.vue
  src/resources/js/pages/menu-management/browse.vue
  src/resources/js/pages/menu-management/builder.vue
Labels: frontend, backend

#486 Task/v3/expand menu item
  src/Controllers/BadasoMenuController.php
  src/Migrations/2021_11_25_100130_add_is_expand_in_badaso_menu_items_table.php
  src/resources/js/assets/scss/page/_menu-management.scss
  src/resources/js/components/BadasoSidebarMenu.vue
  src/resources/js/components/BadasoSidebarMenuCallback.vue
  src/resources/js/pages/menu-management/browse.vue
  src/resources/js/pages/menu-management/builder.vue
Labels: frontend, backend
